/*
 * Modbus.h
 *
 * Created: 5.7.2015 22:55:14
 *  Author: Markus
 */ 

// defines all constants
// in own file because main file would be cluttered otherwise

#ifndef MODBUS_H_
#define MODBUS_H_

#define MODBUS_ADDRESS_IDX		(0)
#define MODBUS_FUNC_CODE_IDX	(1)

#define MODBUS_READ_COILS				(0x01)
#define MODBUS_READ_DISCRETE_INPUTS		(0x02)
#define MODBUS_READ_HOLDING_REGISTER	(0x03)
#define MODBUS_READ_INPUT_REGISTER		(0x04)
#define MODBUS_WRITE_SINGLE_COIL		(0x05)
#define MODBUS_WRITE_SINGLE_REGISTER	(0x06)
#define MODBUS_READ_EXCEPTION_STATUS	(0x07)
#define MODBUS_DIAGNOSTICS				(0x08)
#define MODBUS_GET_COM_EVENT_COUNTER	(0x0B)
#define MODBUS_GET_COM_EVENT_LOG		(0x0C)
#define MODBUS_WRITE_MULTIPLE_COILS		(0x0F)
#define MODBUS_WRITE_MULTIPLE_REGISTERS	(0x10)
#define MODBUS_REPORT_SERVER_ID			(0x11)
#define MODBUS_READ_DEVICE_ID			(0x2B)


#define MODBUS_ILLEGAL_FUNCTION			(0x01)
#define MODBUS_ILLEGAL_DATA_ADDRESS		(0x02)
#define MODBUS_ILLEGAL_DATA_VALUE		(0x03)
#define MODBUS_DEVICE_FAILURE			(0x04)

#define MODBUS_CHANGE_SLAVE_ADDRESS		(0xCAFE)
#define MODBUS_CHANGE_SERIAL_NUMBER		(0xABBA)

#define MODBUS_SET_OFFSET_ADDRESS		(2000)
#define MODBUS_DEVICE_SERIAL_ADDRESS	(0xBEEF)	


#endif /* MODBUS_H_ */
